require:
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: n

RSpec/DescribedClass:
  Enabled: false

# RSpec/ExampleLength:
#   Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
