before_install: gem update bundler
language: ruby
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
