name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 13 * * 1"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - "3.0"
        - "3.1"
        - "3.2"
        - "3.3"
        - "3.4"
        - ruby
        - head
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Print dependency versions
      run: |
        ruby --version
        bundle list
    - name: Run Rake
      run: bundle exec rake
